#!/bin/bash 

BPT_APP_NAME=`python -c 'import setup; print setup.app_name'`
BPT_APP_VERSION=`python -c 'import setup; print setup.app_version'`

bpt_build() {
    python setup.py install --prefix="$BPT_PKG_PREFIX"
}

bpt_unittest() {
    nosetests -v --with-doctest
}

bpt_clean() {
    python setup.py clean --all
}

